import Head from "next/head"
import { ApolloClient, InMemoryCache, useQuery, gql } from "@apollo/client"

export const getStaticProps = async () => {
  const client = new ApolloClient({
    uri: "https://api.spacex.land/graphql/",
    cache: new InMemoryCache()
  })

  const { data } = await client.query({
    query: gql`
      query GetLaunches {
        launchesPast(limit: 10) {
          id
          mission_name
          launch_date_local
          launch_site {
            site_name_long
          }
          links {
            article_link
            video_link
            mission_patch
          }
          rocket {
            rocket_name
          }
        }
      }
    `
  })

  return {
    props: {
      launches: data.launchesPast
    }
  }
}

// wrap the query in the gql template literal
// const GET_LOCATIONS = gql`
//   query getLocations {
//     locations {
//       id
//       name
//       description
//       photo
//     }
//   }
// `

// const DisplayLocations = () => {
//   const { loading, error, data } = useQuery(GET_LOCATIONS)

//   if (loading) return <p>Loading...</p>
//   if (error) return <p>Error : {error.message}</p>

//   return data.locations.map((item) => (
//     <div key={item.id}>
//       <h3>{item.name}</h3>
//       <img width="400" height="250" alt="location-reference" src={`${item.photo}`} />
//       <br />
//       <b>About this location:</b>
//       <p>{item.description}</p>
//       <br />
//     </div>
//   ))
// }

const HomePage = ({ launches }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>A demo from cf</div>
      {launches.map((item) => (
        <a key={item.id} href={item.links.video_link}>
          {JSON.stringify(item)}

          <h3>{item.mission_name}</h3>
          <p>
            <strong>Launch Date:</strong> {new Date(item.launch_date_local).toLocaleDateString("en-US")}
          </p>
        </a>
      ))}
    </>
  )
}

export default HomePage
